### ISSUE TITLE
Build CSS/Bootstrap frame

### ISSUE THREAD

**Issue by Cheez0id** [Cheez0id/Charity-Locator-Project-P1G7#7]

**Comment by EmiReese** [comment]
I used Materialize to create our frame and then CSS for the details. The design is can be considered done. We can always make changes if needed. 
<img width="1680" alt="Screen Shot 2022-01-08 at 1 54 00 PM" src="https://user-images.githubusercontent.com/87937862/148664966-af166b06-e3bc-4c72-bd10-619444865b7e.png">
